const fs = require('fs')
const path = require('path')

if(!fs.existsSync('public')) {
    fs.mkdirSync('public')
    //copy from ../../data/public
const publicPath = path.resolve(__dirname, '../../data/public')
    fs.cpSync(publicPath, 'public', { recursive: true, force: true })
    console.log("Copied public files from data directory")
}

// Create empty tamagui.css if it doesn't exist (needed for build)
const tamaguiCss = path.join(__dirname, 'public', 'tamagui.css')
if (!fs.existsSync(tamaguiCss)) {
    fs.writeFileSync(tamaguiCss, '/* Generated by prepare.js */')
    console.log("Created empty tamagui.css")
}
